#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -std=c++20 -fexceptions -mtune=skylake -pipe
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -s -lglfw -lGLEW -lEGL -lGLU -lGL

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O3
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS)
OBJDIR_RELEASE = obj
DEP_RELEASE = 
OUT_RELEASE = bin/minecraft-clone

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -Og -DDEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj
DEP_DEBUG = 
OUT_DEBUG = bin/minecraft-clone

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/VertexBuffer.o $(OBJDIR_RELEASE)/src/Chunk.o $(OBJDIR_RELEASE)/src/ChunkMesh.o $(OBJDIR_RELEASE)/src/ErrorFeedback.o $(OBJDIR_RELEASE)/src/IndexBuffer.o $(OBJDIR_RELEASE)/src/Renderer.o $(OBJDIR_RELEASE)/src/Shader.o $(OBJDIR_RELEASE)/src/Texture.o $(OBJDIR_RELEASE)/src/VertexArray.o $(OBJDIR_RELEASE)/src/Camera.o $(OBJDIR_RELEASE)/src/VertexBufferLayout.o $(OBJDIR_RELEASE)/src/Window.o $(OBJDIR_RELEASE)/src/World.o $(OBJDIR_RELEASE)/src/vendor/stb_image/stb_image.o $(OBJDIR_RELEASE)/Main.o

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/VertexBuffer.o $(OBJDIR_DEBUG)/src/Chunk.o $(OBJDIR_DEBUG)/src/ChunkMesh.o $(OBJDIR_DEBUG)/src/ErrorFeedback.o $(OBJDIR_DEBUG)/src/IndexBuffer.o $(OBJDIR_DEBUG)/src/Renderer.o $(OBJDIR_DEBUG)/src/Shader.o $(OBJDIR_DEBUG)/src/Texture.o $(OBJDIR_DEBUG)/src/VertexArray.o $(OBJDIR_DEBUG)/src/Camera.o $(OBJDIR_DEBUG)/src/VertexBufferLayout.o $(OBJDIR_DEBUG)/src/Window.o $(OBJDIR_DEBUG)/src/World.o $(OBJDIR_DEBUG)/src/vendor/stb_image/stb_image.o $(OBJDIR_DEBUG)/Main.o

all: release debug

clean: clean_release clean_debug

before_release: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/src/vendor/stb_image || mkdir -p $(OBJDIR_RELEASE)/src/vendor/stb_image
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/VertexBuffer.o: src/VertexBuffer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/VertexBuffer.cpp -o $(OBJDIR_RELEASE)/src/VertexBuffer.o

$(OBJDIR_RELEASE)/src/Chunk.o: src/Chunk.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Chunk.cpp -o $(OBJDIR_RELEASE)/src/Chunk.o

$(OBJDIR_RELEASE)/src/ChunkMesh.o: src/ChunkMesh.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ChunkMesh.cpp -o $(OBJDIR_RELEASE)/src/ChunkMesh.o

$(OBJDIR_RELEASE)/src/ErrorFeedback.o: src/ErrorFeedback.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ErrorFeedback.cpp -o $(OBJDIR_RELEASE)/src/ErrorFeedback.o

$(OBJDIR_RELEASE)/src/IndexBuffer.o: src/IndexBuffer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/IndexBuffer.cpp -o $(OBJDIR_RELEASE)/src/IndexBuffer.o

$(OBJDIR_RELEASE)/src/Renderer.o: src/Renderer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Renderer.cpp -o $(OBJDIR_RELEASE)/src/Renderer.o

$(OBJDIR_RELEASE)/src/Shader.o: src/Shader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Shader.cpp -o $(OBJDIR_RELEASE)/src/Shader.o

$(OBJDIR_RELEASE)/src/Texture.o: src/Texture.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Texture.cpp -o $(OBJDIR_RELEASE)/src/Texture.o

$(OBJDIR_RELEASE)/src/VertexArray.o: src/VertexArray.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/VertexArray.cpp -o $(OBJDIR_RELEASE)/src/VertexArray.o

$(OBJDIR_RELEASE)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Camera.cpp -o $(OBJDIR_RELEASE)/src/Camera.o

$(OBJDIR_RELEASE)/src/VertexBufferLayout.o: src/VertexBufferLayout.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/VertexBufferLayout.cpp -o $(OBJDIR_RELEASE)/src/VertexBufferLayout.o

$(OBJDIR_RELEASE)/src/Window.o: src/Window.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Window.cpp -o $(OBJDIR_RELEASE)/src/Window.o

$(OBJDIR_RELEASE)/src/World.o: src/World.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/World.cpp -o $(OBJDIR_RELEASE)/src/World.o

$(OBJDIR_RELEASE)/src/vendor/stb_image/stb_image.o: src/vendor/stb_image/stb_image.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/vendor/stb_image/stb_image.cpp -o $(OBJDIR_RELEASE)/src/vendor/stb_image/stb_image.o

$(OBJDIR_RELEASE)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Main.cpp -o $(OBJDIR_RELEASE)/Main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/src/vendor/stb_image
	rm -rf $(OBJDIR_RELEASE)

before_debug: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/src/vendor/stb_image || mkdir -p $(OBJDIR_DEBUG)/src/vendor/stb_image
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/VertexBuffer.o: src/VertexBuffer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/VertexBuffer.cpp -o $(OBJDIR_DEBUG)/src/VertexBuffer.o

$(OBJDIR_DEBUG)/src/Chunk.o: src/Chunk.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Chunk.cpp -o $(OBJDIR_DEBUG)/src/Chunk.o

$(OBJDIR_DEBUG)/src/ChunkMesh.o: src/ChunkMesh.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ChunkMesh.cpp -o $(OBJDIR_DEBUG)/src/ChunkMesh.o

$(OBJDIR_DEBUG)/src/ErrorFeedback.o: src/ErrorFeedback.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ErrorFeedback.cpp -o $(OBJDIR_DEBUG)/src/ErrorFeedback.o

$(OBJDIR_DEBUG)/src/IndexBuffer.o: src/IndexBuffer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/IndexBuffer.cpp -o $(OBJDIR_DEBUG)/src/IndexBuffer.o

$(OBJDIR_DEBUG)/src/Renderer.o: src/Renderer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Renderer.cpp -o $(OBJDIR_DEBUG)/src/Renderer.o

$(OBJDIR_DEBUG)/src/Shader.o: src/Shader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Shader.cpp -o $(OBJDIR_DEBUG)/src/Shader.o

$(OBJDIR_DEBUG)/src/Texture.o: src/Texture.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Texture.cpp -o $(OBJDIR_DEBUG)/src/Texture.o

$(OBJDIR_DEBUG)/src/VertexArray.o: src/VertexArray.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/VertexArray.cpp -o $(OBJDIR_DEBUG)/src/VertexArray.o

$(OBJDIR_DEBUG)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Camera.cpp -o $(OBJDIR_DEBUG)/src/Camera.o

$(OBJDIR_DEBUG)/src/VertexBufferLayout.o: src/VertexBufferLayout.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/VertexBufferLayout.cpp -o $(OBJDIR_DEBUG)/src/VertexBufferLayout.o

$(OBJDIR_DEBUG)/src/Window.o: src/Window.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Window.cpp -o $(OBJDIR_DEBUG)/src/Window.o

$(OBJDIR_DEBUG)/src/World.o: src/World.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/World.cpp -o $(OBJDIR_DEBUG)/src/World.o

$(OBJDIR_DEBUG)/src/vendor/stb_image/stb_image.o: src/vendor/stb_image/stb_image.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/vendor/stb_image/stb_image.cpp -o $(OBJDIR_DEBUG)/src/vendor/stb_image/stb_image.o

$(OBJDIR_DEBUG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Main.cpp -o $(OBJDIR_DEBUG)/Main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/src/vendor/stb_image
	rm -rf $(OBJDIR_DEBUG)

.PHONY: before_release after_release clean_release before_debug after_debug clean_debug

