#ifndef TEXTURECOORDINATES_H
#define TEXTURECOORDINATES_H

// BLOCK_AIR (0)
// textureless

// BLOCK_GRASS (1)
#define TEXCOORDS_GRASS_TOP_TL 0.0f, 1.0f
#define TEXCOORDS_GRASS_TOP_TR 0.5f, 1.0f
#define TEXCOORDS_GRASS_TOP_BR 0.5f, 0.5f
#define TEXCOORDS_GRASS_TOP_BL 0.0f, 0.5f

#define TEXCOORDS_GRASS_SIDE_TL 0.5f, 1.0f
#define TEXCOORDS_GRASS_SIDE_TR 1.0f, 1.0f
#define TEXCOORDS_GRASS_SIDE_BR 1.0f, 0.5f
#define TEXCOORDS_GRASS_SIDE_BL 0.5f, 0.5f

#define TEXCOORDS_GRASS_BOTTOM_TL 0.0f, 0.5f
#define TEXCOORDS_GRASS_BOTTOM_TR 0.5f, 0.5f
#define TEXCOORDS_GRASS_BOTTOM_BR 0.5f, 0.0f
#define TEXCOORDS_GRASS_BOTTOM_BL 0.0f, 0.0f

// BLOCK_DIRT (2)
#define TEXCOORDS_DIRT_TL TEXCOORDS_GRASS_BOTTOM_TL
#define TEXCOORDS_DIRT_TR TEXCOORDS_GRASS_BOTTOM_TR
#define TEXCOORDS_DIRT_BR TEXCOORDS_GRASS_BOTTOM_BR
#define TEXCOORDS_DIRT_BL TEXCOORDS_GRASS_BOTTOM_BL

// BLOCK_STONE (3)
#define TEXCOORDS_STONE_TL 0.5f, 0.5f
#define TEXCOORDS_STONE_TR 1.0f, 0.5f
#define TEXCOORDS_STONE_BR 1.0f, 0.0f
#define TEXCOORDS_STONE_BL 0.5f, 0.0f
#endif // TEXTURECOORDINATES_H
